### ISSUE TITLE
Vagner - There is no real slippage protection on the protocol funds when swaps are done

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#354]
Vagner

high

# There is no real slippage protection on the protocol funds when swaps are done
## Summary
Every swap that is done in the `SwapRouter.sol` on every adapter, doesn't use any slippage protection and it specifies in the documentation that the swaps should be happening only when users are withdrawing funds from the `LMPVaultRouter.sol` which provide slippage protection, but that is not the case.
## Vulnerability Detail
It is specified in the README that the withdraw flow should always start from `LMPVaultRouter.sol` which forces an account for slippage 
https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/swapper/README.md
but in reality that is not the case. Every function that is used in the withdrawing process in `LMPVaultRouter.sol` is using slippage only for the shares of the specific vaults 
https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVaultRouter.sol#L27-L34
https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVaultRouter.sol#L40-L46
https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVaultRouter.sol#L63-L69
https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVaultRouter.sol#L76-L80
https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVaultRouter.sol#L90
Even if the user is somewhat protected cause he can specify a minimum amount of funds to be taken out when he is doing withdraws, the protocol is at risk, since if it doesn't have enough `idle` funds to pay the user it calls `withdrawBaseAsset` on the `DestinationVault` to swap assets
https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L483
Because of the fact that every swap is done with 0 protection against sandwich attacks 
https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/DestinationVault.sol#L273
every trade done by the protocol with the protocol funds on every withdraw can be sandwich attacked really easily, so the trade would be against the favor of the protocol, on every adapter used. In the case where this would happen multiple times, there could be the case where the protocol could get insolvent and would not have enough funds to pay back the users, since trades would get sandwich attacked and funds would be lost on every trade. Because of that it could even get to some users not being able to withdraw assets from the protocol because of the insolvency, which hurts the users and the protocol at the same time.
## Impact
Impact is a high one because of the insolvency problems
## Code Snippet
https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/DestinationVault.sol#L273
## Tool used

Manual Review

## Recommendation
Consider implementing some slippage to protect the protocol funds, cause the way the protocol is doing swaps right now is very risky in the long run.

Duplicate of #461

**Comment by VagnerAndrei26** [comment]
Escalate
I escalate my issue as a dup of https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/461, in case it gets accepted. As stated also in https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/461 , this issue speaks about the risk of the entire protocol of losing funds due to no slippage protection on every trade, users are protected because they can specify slippage, but the protocol does every swap without any real protection which could hurt it in the long run.

**Comment by sherlock-admin2** [comment]
> Escalate
> I escalate my issue as a dup of https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/461, in case it gets accepted. As stated also in https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/461 , this issue speaks about the risk of the entire protocol of losing funds due to no slippage protection on every trade, users are protected because they can specify slippage, but the protocol does every swap without any real protection which could hurt it in the long run.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Planning to reject escalation, same comment applies as #461

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #461

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [VagnerAndrei26](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/354/#issuecomment-1748769089): rejected
