### ISSUE TITLE
BTK - Missing access control on #ExtraRewarder.getReward()

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-06-tokemak-judging#369]
BTK

medium

# Missing access control on #ExtraRewarder.getReward()
## Summary

**`ExtraRewarder.getReward()`** allows users to be claimed for which is not what the protocol inteded and it will lead to undesired consequences.

## Vulnerability Detail

**Note (This was confirmed by the sponsor):** *"Ah I see, yes that would be true and not desired ......... could have undesired consequences for that user."*

The **`getReward()`** function implementation:

```solidity
    function getReward(address account) public nonReentrant {
        _updateReward(account);
        _getReward(account);
    }
```

#### Case 1: Assume an extra rewarder with **`rewardToken == toke`**, **`tokeLockDuration` == 0**.

```solidity
    function getRewardWrapper(address user) public {
        rewarder.exposed_updateReward(user);
        rewarder.exposed_getRewardWrapper(user);
    }

    function test_AliceClaimsForBob() public {
        address toke = address(systemRegistry.toke());
        GPToke gPToke = _setupGpTokeAndTokeRewarder();
        _runDefaultScenarioGpToke();

        vm.prank(operator);
        rewarder.setTokeLockDuration(0);

        // Alice is the attacker in this scenario
        address ALICE = makeAddr("ALICE");
        // BOB is a long-term staker
        address BOB = makeAddr("BOB");

        assertEq(IERC20(toke).balanceOf(BOB), 0);

        // Alice called getReward() to claim Bob reward on his behalf.
        vm.prank(ALICE);
        getRewardWrapper(BOB);

        // Bob rewards claimed
        assertEq(IERC20(toke).balanceOf(BOB), 250000);
    }
```

***Result:***

```solidity
Test result: ok. 1 passed; 0 failed; finished in 7.20s
```

***Test Setup:***

- **`cd v2-core-audit-2023-07-14`**
- **`forge test --match-contract _getReward --match-test test_AliceClaimsForBob`**

#### Case 2: Bob wanted to wait until **`tokeLockDuration == 0`** to withdraw his rewards

```solidity
    function test_AliceStakeForBob() public {
        address toke = address(systemRegistry.toke());
        GPToke gPToke = _setupGpTokeAndTokeRewarder();
        _runDefaultScenarioGpToke();

        vm.prank(operator);
        rewarder.setTokeLockDuration(30 days);

        // Alice is the attacker in this scenario
        address ALICE = makeAddr("ALICE");
        // BOB is normal user
        address BOB = makeAddr("BOB");

        // Bob didn't want to stake but to wait until the tokeLockDuration ends to withdraw his rewards

        // Alice called getReward() to stake Bob reward on his behalf.
        vm.prank(ALICE);
        getRewardWrapper(BOB);

        // Bob's reward are now locked in GPToke
        assertEq(gPToke.balanceOf(BOB), 262374);
    }
```

***Result:***

```solidity
Test result: ok. 1 passed; 0 failed; finished in 8.00s
```

***Test Setup:***

- **`cd v2-core-audit-2023-07-14`**
- **`forge test --match-contract _getReward --match-test test_AliceStakeForBob`**

This vulnerability can disrupt the long-term strategies of users who rely on accumulating staking tokens over time, as the attack hinders their ability to do so effectively, and give everyone control over the users rewards.

## Impact

- Users who rely on a long-term strategy of accumulating rewards over time could be adversely affected. Malicious users could claim rewards prematurely, disrupting the intended accumulation process and strategy.
- Users may need to spend additional gas (Deployment chain is the mainnet) and incur transaction costs to correct the situation.
- Depending on the jurisdiction and tax regulations, claiming rewards on behalf of others could have tax implications for the victim.
- Anyone can lock other users rewards into GPToke.
- The unexpected behavior caused by this vulnerability could affect the stability and reliability of the protocol. Users might lose trust in the platform if they experience such issues.

## Code Snippet

- [ExtraRewarder.sol#L53-L56](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/rewarders/ExtraRewarder.sol#L53-L56)

## Tool used

Manual Review

## Recommendation

We recommend updating the function as follow since it should only be callable by the main rewarder or the owner of the account: 

```solidity
    function getReward(address account) public nonReentrant {
        require(msg.sender == mainReward || msg.sender == account, "Can't claim for others");
        _updateReward(account);
        _getReward(account);
    }
```

**Comment by securitygrid** [comment]
Escalate
This issue is low/info. There is no real impact.

> Anyone can lock other users rewards into GPToke.

Wouldn't rewards be locked if the user calls ExtraRewarder.getReward himself?

**Comment by sherlock-admin2** [comment]
> Escalate
> This issue is low/info. There is no real impact.
> 
> > Anyone can lock other users rewards into GPToke.
> 
> Wouldn't rewards be locked if the user calls ExtraRewarder.getReward himself?
> 
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by xiaoming9090** [comment]
This issue (https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/369) and the other duplicates (https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/177, https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/479, https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/539) only describe an attack path where anyone could call the `getReward` of the LMPVault's ExtraRewarder contract on behalf of someone else. When someone does so, the extra reward tokens will simply send to the account address, which does not constitute a loss of assets. Thus, these issues are Low/Informational.

Also, the LMPVault's ExtraRewarder does not hold TOKE. Only the MainRewarder contract holds TOKE. Thus, the scenario described here is invalid.

**Comment by bizzyvinci** [comment]
Wrong access control is an issue by itself. And there are 3 proofs that it was not intended to be callable by anyone.

1. The liquidation mechanism assumes the right access control and causes issues as pointed out by #738. Although liquidation relies on Convex/Aura Rewarder, we can imply that the protocol expects that Tokemak's Rewarder.getReward access is controlled.
2. [MainRewarder.getReward](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/rewarders/MainRewarder.sol#L101) has access control limited to owner or the stakeTracker. stakeTracker is accepted because it is used in [token transfers](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L844) and [claimRewards](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L541). These have access control and claim extra rewards.
3. Sponsor confirmed.

Moreover, building and integration with a wrong assumption as they did in point 1 could lead to loss of funds. This could reasonably happen with ExtraRewarder cause of how MainRewarder is used in [_updateDebtReporting](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L771-L776)

**Comment by 0xbtk** [comment]
> This issue (#369) and the other duplicates (#177, #479, #539) only describe an attack path where anyone could call the `getReward` of the LMPVault's ExtraRewarder contract on behalf of someone else. When someone does so, the extra reward tokens will simply send to the account address, which does not constitute a loss of assets. Thus, these issues are Low/Informational.

This issue doesn't concern the loss of assets; otherwise, it would have been a high. Instead, it revolves around the undesirable situation where anyone can control over users rewards.

> Also, the LMPVault's ExtraRewarder does not hold TOKE. Only the MainRewarder contract holds TOKE. Thus, the scenario described here is invalid.

Could you please provide more details on this? I recall a developer's comment mentioning that certain ExtraRewarders might have the toke token as the mainReward. Perhaps, we should ping the sponsor to hear his thoughts on this.

**Comment by Trumpero** [comment]
The reason that I mark it as a Medium issue because the following reason: 
> The lack of access control will allow for malicious users to manipulate the reward accounts of others and potentially allow for users to [stake](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/rewarders/AbstractRewarder.sol#L372-L375) the accounts of others, locking the funds for a period of time without permission.

@xiaoming9090 can u provide more detail why the ExtraRewarder doesn't hold TOKE ?

**Comment by securitygrid** [comment]
If `durationInBlock` is greater than 0, it makes no difference whoever calls `getReward` and will be staked. If `durationInBlock` is set to 0 by the manager, it will only be affected if the tx with durationInBlock set to 0 is front-runned. But this has little impact.

**Comment by Trumpero** [comment]
As the `_tokeLockDuration` is subject to modification, it's possible that some users are aware of this alteration and might not wish to lock their tokens for the previous duration. However, another party could potentially lock it on their behalf, leading to potential negative consequences for the users.

**Comment by xiaoming9090** [comment]
> The reason that I mark it as a Medium issue because the following reason:
> 
> > The lack of access control will allow for malicious users to manipulate the reward accounts of others and potentially allow for users to [stake](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/rewarders/AbstractRewarder.sol#L372-L375) the accounts of others, locking the funds for a period of time without permission.
> 
> @xiaoming9090 can u provide more detail why the ExtraRewarder doesn't hold TOKE ?

@Trumpero During my discussion with the sponsor, I got the following information from them:

> DestinationVault MainRewarder: WETH
> LMPVault MainRewarder: TOKE + optional whitelisted extra reward tokens (through the ExtraRewarders)

There are two (2) reward systems in the protocol. One for the LMPVault, and another for the DestinationVault.
1) For DestinationVault, it only supports WETH and no extra rewards. Thus, this issue does not affect the DV.
2) For LMPVault, the TOKE is held in the MainRewarder contract, not the ExtraRewarder Contract. ExtraRewarder contract is for holding other optional reward tokens apart from TOKE.

**Comment by Evert0x** [comment]
@Trumpero does the reply of xiaoming affect your opinion that this issue should be medium? 

Also, where did this snippet come from?
> The lack of access control will allow for malicious users to manipulate the reward accounts of others and potentially allow for users to [stake](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/rewarders/AbstractRewarder.sol#L372-L375) the accounts of others, locking the funds for a period of time without permission.

Personally I find the impact listed in the impact section is not significant enough to be Medium.

**Comment by Trumpero** [comment]
The snippet is come from another report. 
But due to xiaoming's comment, I think we can mark it as low.

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [securitygrid](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/369/#issuecomment-1746721914): accepted
