### ISSUE TITLE
0x73696d616f - Lost rewards when `StakeTracker` transfers to a contract that can't handle reward tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#386]
0x73696d616f

high

# Lost rewards when `StakeTracker` transfers to a contract that can't handle reward tokens
## Summary
`StakeTracker` tokens automatically receive rewards and stake on transfers, leading to lost tokens when interacting with external smart contracts that can't deal with them (for example, Uniswap).

## Vulnerability Detail
The reward system of `MainRewarder` and `AbstractRewarder` is coupled with the `StakeTracker`, which is either the [`LMPVault`](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L834-L865) or [`DestinationVault`](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/DestinationVault.sol#L335-L353) (only the `LMPVault` is relevant as the shares of the destination vaults always belong to the `LMPVault`). Whenever there is a token transfer, the `from` address withdraws from the rewarder and gets the rewards, while the `to` address stakes. Thus, if the `StakeTracker` tokens are transferred to a smart contract that can't handle the extra reward tokens, it stakes on behalf of this smart contract, whose rewards are then lost when withdrawing the `StakeTracker` tokens out of it.

## Impact
Lost rewards, it's impossible to say how much but should be a significant amount, as there are many DeFi protocols that can't handle the rewards.

## Code Snippet
In the `DestinationVault` (`LMPVault` is similar):
```solidity
function _beforeTokenTransfer(address from, address to, uint256 amount) internal virtual override {
	if (from == to) {
		return;
	}

	if (from != address(0)) {
		_rewarder.withdraw(from, amount, true);
	}
}

function _afterTokenTransfer(address from, address to, uint256 amount) internal virtual override {
	if (from == to) {
		return;
	}

	if (to != address(0)) {
		_rewarder.stake(to, amount);
	}
}
```
The `true` flag means that the rewards are claimed on [`withdraw()`](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/rewarders/MainRewarder.sol#L82), causing stuck rewards when trasferring out of a smart contract that can't handle them.

## Tool used
Vscode
Foundry
Manual Review

## Recommendation
Stake manually instead of on every token transfer. Another option is to transfer the rewards to the `to` address on token transfer instead of claiming to the `from` address, but this would be more confusing.

**Comment by 0x73696d616f** [comment]
Escalate

I don't think it is reasonable that regular users know which contracts they may send the tokens to.
This would very likely lead to loss of funds for many users, which should not be attributed to user mistake, as it is not reasonable to assume they would know all the contracts they may interact with.
For this reason, it should be a valid HIGH.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I don't think it is reasonable that regular users know which contracts they may send the tokens to.
> This would very likely lead to loss of funds for many users, which should not be attributed to user mistake, as it is not reasonable to assume they would know all the contracts they may interact with.
> For this reason, it should be a valid HIGH.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
Disagree with the escalation, as I believe that collecting rewards for the sender when transferring from the vault is the correct behavior. Whenever users transfer vault tokens, they will collect the rewards at that moment. If they transfer to an outside contract that doesn't handle the reward tokens of its vault's token transfers, it is a problem of that contract and is evidently out of scope. Therefore, users should be aware of the recipient address for their transfers, and any incorrect transfers made by users are considered their mistakes.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with Lead Judge's comment. This is a user error. Low issue

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x73696d616f](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/386/#issuecomment-1745404905): rejected
