### ISSUE TITLE
xiaoming90 - Out-of-gas errors might happen during the withdrawal

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#576]
xiaoming90

medium

# Out-of-gas errors might happen during the withdrawal
## Summary

Out-of-gas errors might happen during the withdrawal, resulting in users being unable to withdraw their assets from the vault

## Vulnerability Detail

If all the DVs are in a loss, the code is forced to loop through all the DVs during withdrawal. An out-of-gas error might happen if the number of DVs supported by the LMPVault is significant and the interaction with various external protocols (e.g., Curve, Balancer) consumes much gas. 

In addition, the number of DVs that can be added to the LMPVault is unbounded in the current codebase.

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L448

```solidity
File: LMPVault.sol
448:     function _withdraw(
..SNIP..
468:             // Using pre-set withdrawalQueue for withdrawal order to help minimize user gas
469:             uint256 withdrawalQueueLength = withdrawalQueue.length;
470:             for (uint256 i = 0; i < withdrawalQueueLength; ++i) {
471:                 IDestinationVault destVault = IDestinationVault(withdrawalQueue[i]);
472:                 (uint256 sharesToBurn, uint256 totalDebtBurn) = _calcUserWithdrawSharesToBurn(
473:                     destVault,
474:                     shares,
475:                     info.totalAssetsToPull - Math.max(info.debtDecrease, info.totalAssetsPulled),
476:                     totalVaultShares
477:                 );
478:                 if (sharesToBurn == 0) {
479:                     continue;
480:                 }
481: 
482:                 uint256 assetPreBal = _baseAsset.balanceOf(address(this));
483:                 uint256 assetPulled = destVault.withdrawBaseAsset(sharesToBurn, address(this));
```

## Impact

Users might be unable to withdraw their assets from the vault under the abovementioned conditions.

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L448

## Tool used

Manual Review

## Recommendation

Consider restricting the number of DVs that can be added to the withdrawal queue and perform the necessary benchmark to ensure that an out-of-gas error does not occur after adding new DVs to the queue.

**Comment by xiaoming9090** [comment]
Escalate

Per the judging comment, this issue should be marked as Low instead of Invalid. Please add the "Low" tag to this issue to prevent the protocol team from missing this bug during remediation & avoid miscalculation of my account's valid/invalid ratio.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Per the judging comment, this issue should be marked as Low instead of Invalid. Please add the "Low" tag to this issue to prevent the protocol team from missing this bug during remediation & avoid miscalculation of my account's valid/invalid ratio.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
added low/info tag

**Comment by hrishibhat** [comment]
Result:
Low
Unique
It does not matter if the issue submitted is low or invalid from the label's perspective. Both invalid and low issues are considered the same when calculating the issues ratio.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/576/#issuecomment-1748039279): rejected

**Comment by Evert0x** [comment]
As Sherlock doesn't have a classification for low severity. The low and invalid labels have the same definition. An escalation to change the label from invalid to low has no potential to add value to the judging process from this point of view.

To avoid confusion the "low/info" label will be removed from future judging repos.

Xiaoming90 left 3 of these escalations on different issues, these escalations will be undone. None of these escalations will affect the Watsons escalation ratio.
