### ISSUE TITLE
xiaoming90 - Exact tokens out via `BalancerBeethovenAdapter` might revert

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#584]
xiaoming90

high

# Exact tokens out via `BalancerBeethovenAdapter` might revert
## Summary

The exact tokens out operation via the `BalancerBeethovenAdapter` might fail if the `exactAmountsOut` array contains one or more zero values, resulting in the caller being unable to remove liquidity.

## Vulnerability Detail

For the `BalancerBeethovenAdapter.removeLiquidity` function, it was understood from the sponsor that its purpose is to perform a "variable BPT in, exact tokens out" for the Balancer pools. 

In Balancer terms, this is called a "Custom Exit". The following is extracted from https://docs.balancer.fi/reference/joins-and-exits/pool-exits.html#userdata:

> - Custom Exit (`BPT_IN_FOR_EXACT_TOKENS_OUT`)
>   - User sends an estimated but unknown (computed at run time) quantity of BPT, and receives precise quantities of specified tokens.

Based on the implementation of this function, the caller can specify the exact amount of tokens they want to receive and allow up to `maxLpBurnAmount` number of LP tokens to be burned.

At Lines 165 to 175 below, the function will check that at least one non-zero value is provided in the `exactAmountsOut` array. Otherwise, it will revert. 

Thus, if the `exactAmountsOut` array contains only one non-zero value for the first token while the rest of the tokens are zero, it is considered acceptable by the system as it is exactly how the Balancer's custom exit would behave.

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/BalancerBeethovenAdapter.sol#L151

```solidity
File: BalancerBeethovenAdapter.sol
151:     function removeLiquidity(
152:         IVault vault,
153:         address pool,
154:         address[] calldata tokens,
155:         uint256[] calldata exactAmountsOut,
156:         uint256 maxLpBurnAmount
157:     ) public returns (uint256[] memory actualAmounts) {
158:         bytes memory userData;
159:         if (BalancerUtilities.isComposablePool(pool)) {
160:             userData = abi.encode(ExitKindComposable.EXACT_BPT_IN_FOR_ALL_TOKENS_OUT, maxLpBurnAmount);
161:         } else {
162:             userData = abi.encode(ExitKind.BPT_IN_FOR_EXACT_TOKENS_OUT, exactAmountsOut, maxLpBurnAmount);
163:         }
164: 
165:         bool hasNonZeroAmount = false;
166:         uint256 nTokens = exactAmountsOut.length;
167:         for (uint256 i = 0; i < nTokens; ++i) {
168:             if (exactAmountsOut[i] != 0) {
169:                 hasNonZeroAmount = true;
170:                 break;
171:             }
172:         }
173:         if (!hasNonZeroAmount) {
174:             revert NoNonZeroAmountProvided();
175:         }
176: 
177:         actualAmounts = _withdraw(
178:             vault,
179:             WithdrawParams({
180:                 pool: pool,
181:                 bptAmount: maxLpBurnAmount,
182:                 tokens: tokens,
183:                 amountsOut: exactAmountsOut,
184:                 userData: userData
185:             })
186:         );
187:     }
```

However, if at least one zero value is provided in the `exactAmountsOut` array, the `_withdraw` function triggered at Line 177 above will revert, which is unexpected.

The reason is that the following check within the `_withdraw` function expects to receive all pool tokens after exiting the pool. If a zero value is provided for any of the pool tokens, none of these pool tokens will be sent over. Thus, the before and after balances remain the same, resulting in a revert at Line 337 below.

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/BalancerBeethovenAdapter.sol#L272

```solidity
File: BalancerBeethovenAdapter.sol
272:     function _withdraw(IVault vault, WithdrawParams memory params) private returns (uint256[] memory amountsOut) {
..SNIP..
330:         for (uint256 i = 0; i < nTokens; ++i) {
331:             uint256 assetBalanceBefore = assetBalancesBefore[i]; // @audit-ok
332: 
333:             IERC20 currentToken = poolTokens[i]; // @audit-ok
334:             if (address(currentToken) != pool) {
335:                 uint256 currentBalance = currentToken.balanceOf(address(this));
336: 
337:                 if (currentBalance < assetBalanceBefore + amountsOut[i]) {
338:                     revert BalanceMustIncrease();
339:                 }
340:                 // Get actual amount returned for event, reuse amountsOut array
341:                 amountsOut[i] = currentBalance - assetBalanceBefore;
342:             }
343:         }
```

## Impact

Any callers that use the affected `removeLiquidity` function could not remove liquidity.

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/BalancerBeethovenAdapter.sol#L151

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/BalancerBeethovenAdapter.sol#L272

## Tool used

Manual Review

## Recommendation

Consider one of the following two options to mitigate the issue:

**Option 1**

Avoid using the `_withdraw` function as it expects to receive all pool tokens after exiting the pool. Implement a new withdraw function that could handle one or more zero pool tokens after exiting the pool.

**Option 2**

A workaround is to perform a check within the `removeLiquidity` function to ensure that there are no zero values within the `exactAmountsOut` array. However, this is not recommended as it breaks the original expectation of how a custom exit should work in the first place.

```solidity
bool hasZeroAmount = false;
uint256 nTokens = exactAmountsOut.length;
for (uint256 i = 0; i < nTokens; ++i) {
    if (exactAmountsOut[i] == 0) {
        hasZeroAmount = true;
        break;
    }
}
if (hasZeroAmount) {
    revert ZeroAmountProvided();
}
```

**Comment by xiaoming9090** [comment]
Escalate. This is an error in the code. The protocol team should review it and determine if it indeed causes no impact on other contracts (internal or external) or off-chain components and fix them if necessary.

Another point that I would like to highlight is that based on the judging comment, if this issue indeed has no impact, it should be marked as Low/Informational instead of Invalid. If an issue is technically correct, it should not be marked as invalid due to the following reasons:

1) The protocol team might miss out on valid low/informational issues, which they might be interested in fixing if they have seen them in the first place if they are tagged correctly. During fixing review, some project teams I have worked with in Sherlock are also interested in fixing Low/Information issues.
2) Watson's ratio might unnecessarily be penalized for an issue that is valid in the first place.

**Comment by sherlock-admin2** [comment]
> Escalate. This is an error in the code. The protocol team should review it and determine if it indeed causes no impact on other contracts (internal or external) or off-chain components and fix them if necessary.
> 
> Another point that I would like to highlight is that based on the judging comment, if this issue indeed has no impact, it should be marked as Low/Informational instead of Invalid. If an issue is technically correct, it should not be marked as invalid due to the following reasons:
> 
> 1) The protocol team might miss out on valid low/informational issues, which they might be interested in fixing if they have seen them in the first place if they are tagged correctly. During fixing review, some project teams I have worked with in Sherlock are also interested in fixing Low/Information issues.
> 2) Watson's ratio might unnecessarily be penalized for an issue that is valid in the first place.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
Hello @xiaoming9090, thank you for your feedback on my judging. I appreciate your input, and I will take more care when evaluating issues as low or invalid in the future.

Regarding this specific issue, I believe it should be categorized as low. Here's my reasoning:
In my view, if a function is actually used in a larger codebase within Tokemak and that codebase is not currently within the scope of the audit, the issue should still be marked as low. This approach is similar to the treatment of view functions. We cannot determine whether a view function can be used in a larger codebase or not. Therefore, it would be unfair to competitors who submit view-related issues and do not receive any rewards. That's why I have categorized this report as low. 

Tks,

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue state.

It's unclear to me why this has high severity impact. The function call reverts based on a function argument, it seems like the function argument can be adjusted to mitigate this behavior. I don't see where the potential loss can occur.

**Comment by Evert0x** [comment]
Result:
Unique
Invalid

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/584/#issuecomment-1748036710): rejected
