### ISSUE TITLE
xiaoming90 - frxETH is loosely pegged to ETH

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#588]
xiaoming90

high

# frxETH is loosely pegged to ETH
## Summary

`EthPeggedOracle` contract should not be used as the oracle for the frxETH as it is loosely pegged to ETH. If the price of frxETH depeg while the oracle continues to report a price of 1:1, the vaults will be overvalued or undervalued, leading to a loss of assets for the vault shareholders.

## Vulnerability Detail

Based on the codebase, the `EthPeggedOracle` is intended to be configured as the oracle for the frxETH.

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/test/oracles/RootOracleIntegrationTest.t.sol#L247

```solidity
File: RootOracleIntegrationTest.t.sol
157:         ethPegOracle = new EthPeggedOracle(systemRegistry);
..SNIP..
244:         // Eth 1:1 setup
245:         priceOracle.registerMapping(WETH9_ADDRESS, IPriceOracle(address(ethPegOracle)));
246:         priceOracle.registerMapping(CURVE_ETH, IPriceOracle(address(ethPegOracle)));
247:         // priceOracle.registerMapping(FRXETH_MAINNET, IPriceOracle(address(ethPegOracle)));
```

As a result, frxETH will always be 1:1 to ETH in the system. However, the frxETH:ETH is not always 1:1. At the time of the audit, one frxETH is worth 0.998 ETH in the Curve Pool.

frxETH is designed to be a stablecoin that is loosely pegged to ETH. This means the price of frxETH could depeg from time to time based on current market conditions.

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/oracles/providers/EthPeggedOracle.sol#L17

```solidity
File: EthPeggedOracle.sol
11: /// @title Price oracle for tokens we want to configure 1:1 to ETH. WETH for example
12: /// @dev getPriceEth is not a view fn to support reentrancy checks. Dont actually change state.
13: contract EthPeggedOracle is SystemComponent, IPriceOracle {
14:     constructor(ISystemRegistry _systemRegistry) SystemComponent(_systemRegistry) { }
15: 
16:     /// @inheritdoc IPriceOracle
17:     function getPriceInEth(address) external pure returns (uint256 price) {
18:         price = 1e18;
19:     }
20: }
```

## Impact

The protocol relies on the oracle to provide accurate pricing for many critical operations, such as determining the debt values of DV, calculators/stats used during the rebalancing process, NAV/shares of the LMPVault, and determining how much assets the users should receive during withdrawal.

If the price of frxETH depeg while the oracle continues to report a price of 1:1, the vaults will be overvalued or undervalued, depending on the direction of the price, leading to users being able to withdraw more or fewer assets than expected. Malicious users might also be able to arbitrage the difference for their own gain at the expense of the vault shareholders. 

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/oracles/providers/EthPeggedOracle.sol#L17

## Tool used

Manual Review

## Recommendation

Avoid using the `EthPeggedOracle` as the oracle for frxETH.

Consider taking reference from the newly [`sfrxEthFraxOracle`](https://etherscan.io/address/0xB9af7723CfBd4469A7E8aa60B93428D648Bda99d#code) deployed by Frax that obtains prices from the following two sources:

1. Uniswap V3 time-weighted average price (TWAP) of frxETH/FRAX (TWAP duration currently is 15 minutes), and the Chainlink [FRAX/USD Oracle](https://etherscan.io/address/0xB9E1E3A9feFf48998E45Fa90847ed4D467E8BcfD).
2. The exponential moving average (EMA) of the [frxETH/ETH Curve Pool](https://curve.fi/#/ethereum/pools/frxeth) (EMA time currently is 2 hours), and the [Chainlink ETH/USD Oracle](https://etherscan.io/address/0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419).

More information can be found [here](https://hackmd.io/@PrismaRisk/sfrxETH#431-Understanding-the-Oracle)

**Comment by xiaoming9090** [comment]
Escalate

The link provided in the judging comment is incorrect as it shows that the oracle of FRAX was set to chainlink oracle, not frxETH, so there is a misunderstanding. This issue is related to frxETH.

```
priceOracle.registerMapping(FRAX_MAINNET, IPriceOracle(address(chainlinkOracle)));
```

FRAX and frxETH are two different tokens. Following are the details for reference:

- FRAX, a USD pegged asset. The first stablecoin pegged to a basket of consumer goods creating its own unit of account separate from any nation state denominated money. 
- FraxEther (frxETH), pegged to ETH for use as a replacement for WETH in smart contracts.

Thus, this is a valid High issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The link provided in the judging comment is incorrect as it shows that the oracle of FRAX was set to chainlink oracle, not frxETH, so there is a misunderstanding. This issue is related to frxETH.
> 
> ```
> priceOracle.registerMapping(FRAX_MAINNET, IPriceOracle(address(chainlinkOracle)));
> ```
> 
> FRAX and frxETH are two different tokens. Following are the details for reference:
> 
> - FRAX, a USD pegged asset. The first stablecoin pegged to a basket of consumer goods creating its own unit of account separate from any nation state denominated money. 
> - FraxEther (frxETH), pegged to ETH for use as a replacement for WETH in smart contracts.
> 
> Thus, this is a valid High issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
My mistake, as I checked with the wrong address of the token. However, I believe this issue is invalid or informational and shouldn't be accepted as valid. The line mentioned in the test file was commented and disabled, so it is not intended to use `ethPegOracle` for the FRXETH token. Furthermore, the whole issue is from a test file, which is out of scope. The code snippet in the report is about `ethPegOracle` and it doesn't have any vulnerabilities.
Only issues from the protocol's contracts should be considered in scope. The risk that the protocol uses the wrong oracle contract for a token always exists, whether they wrote it in the test or not. Therefore, it can't be considered as valid.

**Comment by Trumpero** [comment]
@codenutt I believe you should take a look at it to secure the integration with FRXETH

**Comment by codenutt** [comment]
For sure, thanks both! Only thing we have planned to go live with is weth using the pegged oracle.

**Comment by Evert0x** [comment]
Planning to reject escalation and keep report invalid as the issue is reported in a test file (out of scope)

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/588/#issuecomment-1748035712): rejected
