### ISSUE TITLE
xiaoming90 - `noNavDecrease` modifier might cause withdrawal to revert

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#614]
xiaoming90

high

# `noNavDecrease` modifier might cause withdrawal to revert
## Summary

The `noNavDecrease` modifier might cause some withdrawals to revert under certain market conditions.

## Vulnerability Detail

The following is the function call flow when a user withdraws when there are insufficient `totalIdle` assets in the LMPVault.

```solidity
LMPVaultRouterBase.withdraw
└─ LMPVault.withdraw
   └─ LMPVault._withdraw
      └─ DestinationVault.withdrawBaseAsset
         ├─ DestinationVault._burnUnderlyer
         │  └─ CurveV2FactoryCryptoAdapter.removeLiquidity
         │     └─ Curve Pool's remove_liquidity()
         └─ SwapRouter.swapForQuote
            └─ IUniswapV3SwapRouter.exactInput (Swap Non-based tokens to Based tokens)
```

In summary, the LMPVault will burn its DV shares, which in turn redeem the underlying LP tokens from the DEX (e.g. Curve) to retrieve back the tokens in proportion. The returned tokens contain based assets and non-based assets. The non-based assets, such as wstETH, will be swapped at the pre-defined DEX (e.g., Uniswap V3) to based assets (WETH).

The withdraw function of the LMPVault is guarded by the `noNavDecrease` function. If the NAV deviates more than 100 fixed points, the withdraw TX will revert.

Assume the following:

- totalAssets() = 200e18 WETH (Old)
- totalSupply() = 100e18 shares (Old)
- NAV/share = 200e18 * MAX_FEE_BPS / 100e18 = 20000 (Old)
- Lower bound = 19900
- Upper bound = 20100

To determine the changes in total assets ($\Delta totalAssets$) that will cause the NAV to decrease more than 100 fixed points, one could solve the following equation:

$$
\begin{align}
\frac{\Delta totalAssets}{totalSupply} \times 10000 = 100 \\
\frac{\Delta totalAssets}{100e18} \times 10000 = 100 \\
\Delta totalAssets = 1e18
\end{align}
$$

As such, if the total assets decrease more than 1e18 (1 WETH) after the withdrawal, it will trigger and revert. Otherwise, it will not.

This might pose an issue in certain market conditions where the market is volatile and/or liquidity on various DEXs is low. In this case, external protocols/contracts/users configured to withdraw a large portion of assets from the vault might not be able to withdraw from the vault.

Assume that XYZ protocol is configured to automatically redeem 150 WETH worth of shares from the LMPVault when a specific market condition is met. For simplicity's sake, assume that wstETH is pegged to ETH (1:1). After the system redeems the underlying LP tokens, 75 WETH + 75 wstETH are returned by Curve. 75 wstETH would need to be swapped at the pre-defined DEX to WETH.

If the swap results in a loss of more than 1 WETH, the withdrawal will revert. In this case, if slippage is around 1.4% during the swap, the loss will be more than 1 WETH. 

If the current market condition results in the swap across all the DEXs on-chains exceeding a 1.4% slippage rate, the administrator would not be able to find a better route.

XYZ protocol attempts to withdraw 150 WETH will fail.

## Impact

Unable to withdraw from the vault under certain market conditions

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L147

## Tool used

Manual Review

## Recommendation

Ideally, slippage lost from any swap carried out within the withdrawal process should be charged to the user redeeming the LMPVault shares, and it should not affect the NAV/share of the LMPVault. 

As long as the user accepts the slippage lost, the withdrawal should succeed. In the above example, the withdrawal should proceed if XYZ protocol is willing to absorb a slippage loss of up to 5 WETH or more than a slippage rate of 1.4%.

**Comment by xiaoming9090** [comment]
Escalate

The main point of this report is to demonstrate the risks of the `noNavDecrease` modifier. It is a valid issue as long as there is a risk in its current design. It is not about whether the `noNavDecrease` modifier is working correctly or not OR working as per design.

For the users to be able to withdraw later, as mentioned in the judging comment, the market condition market must improve. However, it is incorrect to assume that the market condition will always improve, as it might go downhill and never recover. As such, there must be measures in place to allow users to continue to withdraw their assets under such scenarios, as mentioned in my solution. Otherwise, their assets will be permanently stuck.

Thus, this is a valid High issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The main point of this report is to demonstrate the risks of the `noNavDecrease` modifier. It is a valid issue as long as there is a risk in its current design. It is not about whether the `noNavDecrease` modifier is working correctly or not OR working as per design.
> 
> For the users to be able to withdraw later, as mentioned in the judging comment, the market condition market must improve. However, it is incorrect to assume that the market condition will always improve, as it might go downhill and never recover. As such, there must be measures in place to allow users to continue to withdraw their assets under such scenarios, as mentioned in my solution. Otherwise, their assets will be permanently stuck.
> 
> Thus, this is a valid High issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
#586 has the same root cause

**Comment by Evert0x** [comment]
@Trumpero what's your take on this? Is it the same root cause as #586?

**Comment by xiaoming9090** [comment]
This report is based on a similar wrong assumption as described [here](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/586#issuecomment-1781148962).

Thus, this report is invalid. @Evert0x @Trumpero please proceed to invalid this report and escalation.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/614/#issuecomment-1748033243): rejected
