### ISSUE TITLE
xiaoming90 - Reward tokens will be stuck if it is the same as the base asset

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#616]
xiaoming90

high

# Reward tokens will be stuck if it is the same as the base asset
## Summary

Reward tokens will be stuck if it is the same as the base asset, resulting in a loss of reward tokens for the vault shareholders.

## Vulnerability Detail

When the protocol stakes the LP tokens to external staking protocols (e.g., Convex, Aura, Maverick), the protocol will receive certain reward tokens in return. The `LiquidationRow` will first claim the reward tokens from the staking protocol. During the liquidation, it will swap the reward tokens to WETH (base asset) and queue them to the DestinationVault's mainrewarder.

There is an edge case that the reward tokens received from the staking protocol are the same as the base assets of the DV. For instance, the protocol might receive WETH as a reward.

Per the `LiquidationRow` contract, the only method to queue rewards to DV's mainrewarder is through the `LiquidationRow._performLiquidation` function. There is no other option in the `LiquidationRow` contract without calling this function.

When attempting to queue the WETH rewards to DV via the `LiquidationRow._performLiquidation`, Line 251 will always perform a swap. However, it makes no sense to swap from WETH to WETH. Two possible outcomes might occur, both of which are undesirable:

1) Since the buy token is the same as the sell token, performing a swap on most DEX will result in a revert; OR
2) In the event a swap manages to go through (very unlikely), it will incur a trading fee and slippage.

In the worst-case scenario (1st outcome), the WETH rewards will be stuck within the `LiquidatorRow` contract with no way to queue the WETH rewards to the DV.

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/liquidation/LiquidationRow.sol#L240

```solidity
File: LiquidationRow.sol
240:     function _performLiquidation(
..SNIP..
249:         uint256 length = vaultsToLiquidate.length;
250:         // the swapper checks that the amount received is greater or equal than the params.buyAmount
251:         uint256 amountReceived = IAsyncSwapper(asyncSwapper).swap(params);
..SNIP..
264:         uint256 gasUsedPerVault = (gasBefore - gasleft()) / vaultsToLiquidate.length;
265:         for (uint256 i = 0; i < length; ++i) {
266:             IDestinationVault vaultAddress = vaultsToLiquidate[i];
267:             IMainRewarder mainRewarder = IMainRewarder(vaultAddress.rewarder());
268: 
269:             if (mainRewarder.rewardToken() != params.buyTokenAddress) {
270:                 revert InvalidRewardToken();
271:             }
272: 
273:             uint256 amount = amountReceived * vaultsBalances[i] / totalBalanceToLiquidate;
274: 
275:             // approve main rewarder to pull the tokens
276:             LibAdapter._approve(IERC20(params.buyTokenAddress), address(mainRewarder), amount);
277:             mainRewarder.queueNewRewards(amount);
..SNIP..
281:         }
282:     }
..SNIP..
```

## Impact

Rewards will be stuck within the `LiquidatorRow` contract, leading to a loss of reward tokens for the vault shareholders.

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/liquidation/LiquidationRow.sol#L240

## Tool used

Manual Review

## Recommendation

If the reward tokens queued are the same as the base asset (WETH), there is no need to perform the swap. Thus, it can be skipped.

```diff
function _performLiquidation(
    uint256 gasBefore,
    address fromToken,
    address asyncSwapper,
    IDestinationVault[] memory vaultsToLiquidate,
    SwapParams memory params,
    uint256 totalBalanceToLiquidate,
    uint256[] memory vaultsBalances
) private {
    uint256 length = vaultsToLiquidate.length;
    
+	if (fromToken == <Target DV's baseAsset>) {
+		uint256 amountReceived = totalBalanceToLiquidate;
+ 	} else {
    	// the swapper checks that the amount received is greater or equal than the params.buyAmount
    	uint256 amountReceived = IAsyncSwapper(asyncSwapper).swap(params);
+	}

..SNIP..
    uint256 gasUsedPerVault = (gasBefore - gasleft()) / vaultsToLiquidate.length;
    for (uint256 i = 0; i < length; ++i) {
        IDestinationVault vaultAddress = vaultsToLiquidate[i];
        IMainRewarder mainRewarder = IMainRewarder(vaultAddress.rewarder());

        if (mainRewarder.rewardToken() != params.buyTokenAddress) {
            revert InvalidRewardToken();
        }

        uint256 amount = amountReceived * vaultsBalances[i] / totalBalanceToLiquidate;

        // approve main rewarder to pull the tokens
        LibAdapter._approve(IERC20(params.buyTokenAddress), address(mainRewarder), amount);
        mainRewarder.queueNewRewards(amount);
..SNIP..
    }
}
```

**Comment by xiaoming9090** [comment]
Escalate

In my report, I mentioned two possible outcomes, as shown above.

- If it is the first outcome, the WETH rewards will be stuck within the `LiquidatorRow` contract with no way to queue the WETH rewards to the DV.

- If it is the second outcome, it was mentioned that "for each fromToken, the liquidator can choose which `asyncSwapper` to be used for the swap. So for the case when fromToken = WETH, he can pass some "blank" swapper which does nothing and won't endure the swap fee". For the context of this audit, the `asyncSwapper` to be used is 0x and 1inch, as mentioned by the protocol team (refer to the screenshot below) during our discussion during the audit period. There is no evidence during the audit period that the protocol team is aware of this issue and plans to use a "blank" swapper to work around this bug. Thus, this argument is invalid.

Thus, this issue stands and is a valid High as it leads to loss of assets.

![image](https://github.com/sherlock-audit/2023-06-tokemak-judging/assets/102820284/38a08f62-90bd-45c8-b82d-a6bb69df00b4)

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> In my report, I mentioned two possible outcomes, as shown above.
> 
> - If it is the first outcome, the WETH rewards will be stuck within the `LiquidatorRow` contract with no way to queue the WETH rewards to the DV.
> 
> - If it is the second outcome, it was mentioned that "for each fromToken, the liquidator can choose which `asyncSwapper` to be used for the swap. So for the case when fromToken = WETH, he can pass some "blank" swapper which does nothing and won't endure the swap fee". For the context of this audit, the `asyncSwapper` to be used is 0x and 1inch, as mentioned by the protocol team (refer to the screenshot below) during our discussion during the audit period. There is no evidence during the audit period that the protocol team is aware of this issue and plans to use a "blank" swapper to work around this bug. Thus, this argument is invalid.
> 
> Thus, this issue stands and is a valid High as it leads to loss of assets.
> 
> ![image](https://github.com/sherlock-audit/2023-06-tokemak-judging/assets/102820284/38a08f62-90bd-45c8-b82d-a6bb69df00b4)
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
Hello @xiaoming9090, thank you for the clarification.

In my opinion, the protocol has not specified which AGGREGATOR to use for the swapping in the public documentation/discussion channel. Therefore, utilizing internal discussions for information that might not be known by everyone seems unjust to me.

Additionally, I believe the protocol team might not fully grasp the consequences of this issue, but it can easily be resolved by utilizing an alternative "blank" swapper, as I mentioned in my judgment comment.

Considering the two reasons mentioned above, I believe this issue should be classified as "Information," in my opinion.

Kindly notify @codenutt regarding this matter.

**Comment by xiaoming9090** [comment]
Appreciate your time in reviewing the escalation. Following is my comment:

> In my opinion, the protocol has not specified which AGGREGATOR to use for the swapping in the public documentation/discussion channel. Therefore, utilizing internal discussions for information that might not be known by everyone seems unjust to me.

In the audit contest's repository, it contains several artifacts that indicate that 0x and/or 1inch would be used as the AGGREGATOR:
- https://github.com/sherlock-audit/2023-06-tokemak/tree/main/v2-core-audit-2023-07-14/test/liquidators
- https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/test/utils/Addresses.sol#L33

Based on the above artifacts, one could infer that 0x and/or 1inch would be used as the AGGREGATOR. In addition, if an auditor does not know what protocol the AGGREGATOR points to, it is the responsibility of the auditor to seek additional clarification from the protocol team, which I have done. Other auditors also have an open channel with the protocol team and could also seek clarification from the protocol team if they wish. Thus, I do not see how it is being unfair over here.

> Additionally, I believe the protocol team might not fully grasp the consequences of this issue, but it can easily be resolved by utilizing an alternative "blank" swapper, as I mentioned in my judgment comment.

Using the "blank" swapper is a workaround or solution to the issue I pointed out in the report. Having a workaround or solution does not invalidate the issue unless the protocol team explicitly formally documents this workaround in its source code's comment or makes it aware to us before the audit contest.

**Comment by codenutt** [comment]
@Trumpero We hadn't considered a case where WETH was a reward token. For all the pools and rewarders we have looked at and plan on targeting, that hasn't come up. This is why though the swappers themselves are extensible and we don't have just one option. As we come across new scenarios they can be handled, even if the tokens are already sitting in liquidationrow. Afaik, this isn't an issue for the pools we currently have targeted.

**Comment by Evert0x** [comment]
If I understand correctly, during the audit it was clear that.
1. The protocol is going to use a swapper 
2. It was unclear which swapper was going to be used exactly
3. Based on tests it was clear that 0x and 1inch were considered

Planning to accept escalation and make medium.

The reasons for medium (not high) 
1. Submitter indicates it is an edge case
2. The clarified context indicate 1inch is not really considered

**Comment by Trumpero** [comment]
Hello, @Evert0x, based on my understanding of the sponsor's comment, this does not seem to be an issue for the current pool that Tokemak will integrate with. Additionally, the sponsor has mentioned that the swapper can be extended to accommodate new scenarios, such as WETH. Therefore, I believe the appropriate severity for this should be classified as "Informational."

**Comment by Evert0x** [comment]
If I understand correctly the pools the protocol were planning to integrate with were not known during the audit and were not clarified during the audit (not in public, not in DMs)

**Comment by Trumpero** [comment]
No, the pools that the protocol will integrate with was already specified in the contest documentation.
<img width="775" alt="Screenshot 2023-10-26 at 18 51 45" src="https://github.com/sherlock-audit/2023-06-tokemak-judging/assets/114548871/e29900e4-07d3-46af-8d85-4fc806d2316c">

**Comment by Evert0x** [comment]
Right, so the case depends on the fact if WETH is a reward token in any of these pools, correct?

**Comment by Trumpero** [comment]
Yes

**Comment by Evert0x** [comment]
Ok planning to reject escalation and keep invalid unless @xiaoming9090 can proof that WETH is a reward token in the listed pools.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/616/#issuecomment-1748033022): rejected
