### ISSUE TITLE
nobody2018 - CurveV2FactoryCryptoAdapter.addLiquidity will revert in some cases due to subtraction underflow

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#622]
nobody2018

medium

# CurveV2FactoryCryptoAdapter.addLiquidity will revert in some cases due to subtraction underflow
## Summary

In CurvePool, 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE means ETH. For the convenience of description, we call this address EthAddr. [[CurveV2FactoryCryptoAdapter.addLiquidity](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/CurveV2FactoryCryptoAdapter.sol#L82-L89)](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/CurveV2FactoryCryptoAdapter.sol#L82-L89) will emit the `DeployLiquidity` event at the end. Before the event is emitted, it will call `_updateWethAddress` to update EthAddr to the WETH address.

However, the calling order of `_updateWethAddress` and `_getCoinsBalances` is wrong. [[_getCoinsBalances](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/CurveV2FactoryCryptoAdapter.sol#L206-L210)](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/CurveV2FactoryCryptoAdapter.sol#L206-L210) internally uses EthAddr to get the ETH balance. The `tokens` argument of `_getCoinsBalances` has been updated by `_updateWethAddress`, so there is no EthAddr in `tokens`. Therefore, the correct order should be `_getCoinsBalances` first and then `_updateWethAddress`.

## Vulnerability Detail

```solidity
File: v2-core-audit-2023-07-14\src\destinations\adapters\CurveV2FactoryCryptoAdapter.sol
48:     function addLiquidity(
49:         uint256[] calldata amounts,
50:         uint256 minLpMintAmount,
51:         address poolAddress,
52:         address lpTokenAddress,
53:         IWETH9 weth,
54:         bool useEth
55:     ) public {
......
63:         uint256 nTokens = amounts.length;
64:         address[] memory tokens = new address[](nTokens);
65:         uint256[] memory coinsBalancesBefore = new uint256[](nTokens);
66:         for (uint256 i = 0; i < nTokens; ++i) {
68:             address coin = ICryptoSwapPool(poolAddress).coins(i);
69:->           tokens[i] = coin;
......
73:->           coinsBalancesBefore[i] = coin == LibAdapter.CURVE_REGISTRY_ETH_ADDRESS_POINTER
74:->               ? address(this).balance
75:                 : IERC20(coin).balanceOf(address(this));
76:         }
77: 
78:         uint256 deployed = _runDeposit(amounts, minLpMintAmount, poolAddress, useEth);
79: 
80:         IERC20 lpToken = IERC20(lpTokenAddress);
81: 	    
82:->       _updateWethAddress(tokens, address(weth));
83: 
84:         emit DeployLiquidity(
85:->           _compareCoinsBalances(coinsBalancesBefore, _getCoinsBalances(tokens, weth, useEth), amounts, true),
86:             tokens,
87:             [deployed, lpToken.balanceOf(address(this)), lpToken.totalSupply()],
88:             poolAddress
89:         );
90:         //slither-disable-end reentrancy-events
91:     }
```

L66-76, the `for` loop gets the balance of each coin and stores it in the `coinsBalancesBefore` array. `tokens` store each coin address of the pool, and ETH is `LibAdapter.CURVE_REGISTRY_ETH_ADDRESS_POINTER`.

L78, [[_runDeposit](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/CurveV2FactoryCryptoAdapter.sol#L235-L240)](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/CurveV2FactoryCryptoAdapter.sol#L235-L240) internally calls `pool.add_liquidity` to add liquidity.

L82, [[_updateWethAddress](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/CurveV2FactoryCryptoAdapter.sol#L171-L177)](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/CurveV2FactoryCryptoAdapter.sol#L171-L177) replaces LibAdapter.CURVE_REGISTRY_ETH_ADDRESS_POINTER in tokens with WETH.

L85, [[_getCoinsBalances(tokens, weth, useEth)](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/CurveV2FactoryCryptoAdapter.sol#L204-L211)](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/CurveV2FactoryCryptoAdapter.sol#L204-L211) is called first. Because `tokens` have no `LibAdapter.CURVE_REGISTRY_ETH_ADDRESS_POINTER`.

```solidity
File: v2-core-audit-2023-07-14\src\destinations\adapters\CurveV2FactoryCryptoAdapter.sol
204:         for (uint256 i = 0; i < nTokens; ++i) {
205:             address coin = tokens[i];
206:             if (coin == LibAdapter.CURVE_REGISTRY_ETH_ADDRESS_POINTER) {
207:                 coinsBalances[i] = useEth ? address(this).balance : weth.balanceOf(address(this));
208:             } else {
209:                 coinsBalances[i] = IERC20(coin).balanceOf(address(this));
210:             }
211:         }
```

So L207 is never executed, instead L209 is executed. That is equivalent to `coinsBalances[i] = IERC20(WETH).balanceOf(address(this))`.

Now let's assume such a situation:

The pool has 2 coins. One is ETH, and the other is token1. This contract owns 1e18 ETH and 1.1e18 WETH and 1000e18 token1.

1.  When L66-76 is executed:
    coinsBalancesBefore[0] = 1e18, tokens[0] = ETH
    coinsBalancesBefore[1] = 1000e18, tokens[1] = token1
2.  When L78 is executed:
    `this` contract only has 1.1e18 WETH and some minted pool tokens.
3.  When L82 is executed:
    tokens[0] = ETH => tokens[0] = WETH
    tokens[1] = token1
4.  When L85 is split into 2 calls:
    a. `_getCoinsBalances(tokens, weth, useEth)` returns an array which is called `coinsBalancesAfter`.
        coinsBalancesAfter[0] = 1.1e18
        coinsBalancesAfter[1] = 0
    b. `_compareCoinsBalances` is executed:

```solidity
File: v2-core-audit-2023-07-14\src\destinations\adapters\CurveV2FactoryCryptoAdapter.sol
215:     function _compareCoinsBalances(
216:         uint256[] memory balancesBefore,
217:         uint256[] memory balancesAfter,
218:         uint256[] memory amounts,
219:         bool isLiqDeployment
220:     ) private pure returns (uint256[] memory balanceChange) {
221:         uint256 nTokens = amounts.length;
......
224:         for (uint256 i = 0; i < nTokens; ++i) {
225:             uint256 balanceDiff =
226:->               isLiqDeployment ? balancesBefore[i] - balancesAfter[i] : balancesAfter[i] - balancesBefore[i];
......
232:         }
233:     }
```

L226, isLiqDeployment = true,
`balancesBefore[i] - balancesAfter[i] = coinsBalancesBefore[0] - coinsBalancesAfter[0] = 1e18 - 1.1e18 => underflow`.
## Impact

In the above case, `addLiquidity` will fail due to subtraction underflow.

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/CurveV2FactoryCryptoAdapter.sol#L82-L89

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/destinations/adapters/CurveV2FactoryCryptoAdapter.sol#L226

## Tool used

Manual Review

## Recommendation

```fix
File: v2-core-audit-2023-07-14\src\destinations\adapters\CurveV2FactoryCryptoAdapter.sol
82:+        uint256[] memory coinsBalancesAfter = _getCoinsBalances(tokens, weth, useEth);
82:         _updateWethAddress(tokens, address(weth));
83: 
84:         emit DeployLiquidity(
85:-            _compareCoinsBalances(coinsBalancesBefore, _getCoinsBalances(tokens, weth, useEth), amounts, true),
85:+            _compareCoinsBalances(coinsBalancesBefore, coinsBalancesAfter, amounts, true),
86:             tokens,
87:             [deployed, lpToken.balanceOf(address(this)), lpToken.totalSupply()],
88:             poolAddress
89:         );
```

**Comment by securitygrid** [comment]
Escalate 
The whole library is in the scope. From the test code, we can see that `addLiquidity` will be used.
In the 2023-04-splits contest, there was [an issue](https://github.com/sherlock-audit/2023-04-splits-judging/issues/9)  caused by a library function that is not called by any contract in the scope.

**Comment by sherlock-admin2** [comment]
> Escalate 
> The whole library is in the scope. From the test code, we can see that `addLiquidity` will be used.
> In the 2023-04-splits contest, there was [an issue](https://github.com/sherlock-audit/2023-04-splits-judging/issues/9)  caused by a library function that is not called by any contract in the scope.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
Hello @securitygrid 

Regarding this specific issue, I believe it should be categorized as low. Here's my reasoning:
In my view, if a function is actually used in a larger codebase within Tokemak and that codebase is not currently within the scope of the audit, the issue should still be marked as low. This approach is similar to the treatment of view functions. We cannot determine whether a view function can be used in a larger codebase or not. Therefore, it would be unfair to competitors who submit view-related issues and do not receive any rewards. That's why I have categorized this report as low.

Tks,

**Comment by Evert0x** [comment]
Agree with lead judge. Planning to reject escalation and keep issue state.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [securitygrid](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/622/#issuecomment-1745357443): rejected
