### ISSUE TITLE
xiaoming90 - Over/Under-collection of liquidation fee

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#626]
xiaoming90

high

# Over/Under-collection of liquidation fee
## Summary

Over/Under-collection of liquidation fee lead to a loss of reward for the users or a loss for the protocol team as it cannot recoup the expenses.

## Vulnerability Detail

It is understood from the protocol team that the idea of charging a fee in `LiquidationRow` contract is to be able to recoup the costs of running the liquidation service.

Assume that the price of CVX is $3, and there are 100,000 CVX to be liquidated. This means that it will receive 181 ETH after the swap.

Assume that the liquidation fee is 1%. In this case, 1.8 ETH will be charged as the fee for executing the liquidation. 1.8 ETH is worth around $3000. It is unlikely that the gas fee required to execute the liquidation process (claiming reward + swap + queuing rewards) will cost \$3000. Thus, the liquidation fee will be "over-collected", especially when there is a large number of reward tokens to be swapped in one go.

Note that breaking down the liquidation of reward tokens into smaller chunks or having it executed more frequently so that it will not grow to a huge sum is not a solution to this issue, as the liquidator will end up incurring more gas fees. The most efficient manner is to accumulate the reward tokens to a reasonably large amount and perform the swap in one go.

The root cause of this issue is that the liquidation fee charge is proportional to the reward tokens swapped while the gas needed to execute the liquidation process is more or less constant. For example, the gas needed to swap 10 CVX to WETH and 100,000 CVX to WETH are relatively constant.

![image-20230825133221806](https://user-images.githubusercontent.com/102820284/263186345-9693b182-036e-4e3b-9a65-b0d7ee434fea.png)

On the other hand, the liquidator will not be able to recoup the expenses if the number of reward tokens collected is extremely few.

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/liquidation/LiquidationRow.sol#L240

```solidity
File: LiquidationRow.sol
240:     function _performLiquidation(
..SNIP..
253:         // if the fee feature is turned on, send the fee to the fee receiver
254:         if (feeReceiver != address(0) && feeBps > 0) {
255:             uint256 fee = calculateFee(amountReceived);
256:             emit FeesTransfered(feeReceiver, amountReceived, fee);
257: 
258:             // adjust the amount received after deducting the fee
259:             amountReceived -= fee;
260:             // transfer fee to the fee receiver
261:             IERC20(params.buyTokenAddress).safeTransfer(feeReceiver, fee);
262:         }
```

## Impact

If the liquidation fee is "over-collected", it leads to a loss of reward for the users

If the liquidation fee is "under-collected", it results in a loss for the protocol team as it cannot recoup the expenses.

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/liquidation/LiquidationRow.sol#L240

## Tool used

Manual Review

## Recommendation

Consider performing benchmarks to determine the gas (+ some slight buffer) needed to execute the liquidation process. The estimated gas fee can be obtained by multiplying the gas needed by the gas price obtained on-chain from Chainlink's [Fast Gas feed](https://data.chain.link/ethereum/mainnet/gas/fast-gas-gwei). Finally, add some margin to factor in the cost of running the infrastructure and compensation for the protocol team for maintaining and configuring the infrastructure. This will prevent the over-collecting of liquidation fees.

**Comment by xiaoming9090** [comment]
Escalate

It is not true that there is no evidence as per the judging comment. Attached is the evidence from my discussion with the protocol team that the intention of charging a fee in `LiquidationRow` is to recoup the costs of running the liquidation service. 

![image](https://github.com/sherlock-audit/2023-06-tokemak-judging/assets/102820284/5cfb2a08-1bac-4cc8-878f-02990a9677ee)

Thus, this is a valid High issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> It is not true that there is no evidence as per the judging comment. Attached is the evidence from my discussion with the protocol team that the intention of charging a fee in `LiquidationRow` is to recoup the costs of running the liquidation service. 
> 
> ![image](https://github.com/sherlock-audit/2023-06-tokemak-judging/assets/102820284/5cfb2a08-1bac-4cc8-878f-02990a9677ee)
> 
> Thus, this is a valid High issue.
> 
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
Hello @xiaoming9090, in my opinion, the utilization of the fee collected from Liquidation is contingent upon the protocol's intention. As there is no documentation elucidating the protocol's objectives for the liquidation fee, typical auditors who do not inquire about the sponsor's intentions may assume that this fee serves as a means of generating profit for the protocol.

Considering the aforementioned circumstances, I recommend categorizing this issue as an informational matter since I believe it would be unfair for other users who are unaware of the purpose of the liquidation fee.

@codenutt, could you please verify the validity of the information provided in the message?

**Comment by xiaoming9090** [comment]
Appreciate your time in reviewing the escalation.

> Considering the aforementioned circumstances, I recommend categorizing this issue as an informational matter since I believe it would be unfair for other users who are unaware of the purpose of the liquidation fee.

Regarding the above point, I do not think it is unfair to other users. Like me, the other users also have an open channel to the protocol team and are free to seek clarification from them (e.g., via public contest discord channel or private DM) if they are not aware of the purpose of the liquidation fee. It is the responsibility of the auditor to seek clarification from the protocol team if there is anything they are unsure of and could not be found in the documentation. Thus, this should not be used to downgrade an issue to informational.

**Comment by codenutt** [comment]
> Hello @xiaoming9090, in my opinion, the utilization of the fee collected from Liquidation is contingent upon the protocol's intention. As there is no documentation elucidating the protocol's objectives for the liquidation fee, typical auditors who do not inquire about the sponsor's intentions may assume that this fee serves as a means of generating profit for the protocol.
> 
> Considering the aforementioned circumstances, I recommend categorizing this issue as an informational matter since I believe it would be unfair for other users who are unaware of the purpose of the liquidation fee.
> 
> @codenutt, could you please verify the validity of the information provided in the message?

That is the intention of the fee, yes, though not meant to be exact. Even in the recommendation, the use of buffers, referencing infrastructure costs that can change, it's really a best-effort number.The majority of the gas costs that are going to be incurred are during the claiming of the tokens from Convex/Aura/Maverick. The execution of that is separate from the liquidation itself. It's also likely that claiming from some venues are going to much more expensive than others even if the resulting reward token is the same. I'd also disagree that swapping 10 CVX or 100,000 CVX are gas equivalent. 10 CVX would likely be routed through 1 pool, for 100k an aggregator would likely break that between multiple pools. All of this is to really say that this is a moving target and that tracking it accurately on-chain with the idea that multiple lmpvaults dump into the same liquidation contract, but all swap together, would be excessive. We are emitting gas usage events from here so that we can go back and analyze and make sure we are being covered, utilizing the ability to set fees on the lmpvault, paired with a fee here if necessary.

**Comment by Evert0x** [comment]
The Watson is able to DM the protocol team to seek clarification, but it will not be weighted as much.
> screenshots are not considered sources of truth while judging an issue/escalation especially if they are conflicting with the contest README.

Besides that, considering the complexity of the feature. My opinion is that the Watson is just pointing out a sub-optimal implementation as the feature complete implementation adds an extreme amount of complexity. 

Planning to reject escalation and keep issue state

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/626/#issuecomment-1748031300): rejected
