### ISSUE TITLE
Qeew - Potential vulnerabilities with a 30-Minute Delay in TellorOracle

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#744]
Qeew

high

# Potential vulnerabilities with a 30-Minute Delay in TellorOracle
## Summary

The protocol primarily uses Chainlink as its primary oracle service but falls back to Tellor in case Chainlink is down. However, the Tellor oracle is used with a 30-minute delay, which introduces a  potential risk.

## Vulnerability Detail
In the TellorOracle.sol contract, the following statement is used to retrieve data from the Tellor oracle:

(bytes memory data, uint256 timestamp) = getDataBefore(_queryId, block.timestamp - 30 minutes);

The vulnerability arises from the 30-minute delay in the getPriceInEth function of the TellorOracle contract. This delay means that, in the event of a fallback to Tellor, the system will be using a price that is at least 30 minutes old, which can lead to significant discrepancies in volatile markets.

There is a recent analysis by [Liquity ](https://www.liquity.org/blog/tellor-issue-and-fix) in which they are using 15 minutes for ETH after making some analysis of ETH volatility behaviour. 

Basically, there is a tradeoff between the volatility of an asset and the dispute time. More time is safer to have time to dispute but more likely to read an old value. 

## Impact

The 30-minute delay could lead to a larger differential between the price the system sees and the real market price. This is particularly important in the case of a fallback, as it increases the chances of the system using a stale price. Liquity chose 15 minute to give plenty of time for disputers to respond to fake prices while keeping any adverse impacts on the system to a minimum. Using a 30-minute delay could lead to adverse impacts that Liquity sought to minimize.

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/oracles/providers/TellorOracle.sol#L105

## Tool used

Manual Review

## Recommendation

Reduce the delay to a shorter period, such as 15 minutes, as used by Liquity.

**Comment by xiaoming9090** [comment]
Escalate

For context, the longer the delay period, the less likely a fake price will go through, as fake pricing will likely be disputed. In exchange, the price might be lagged behind the market price. Thus, there is a trade-off between the volatility of an asset and the dispute time. The recommended delay period I have seen from online texts/documentation ranges between 15 min and 20 min. 

However, in the current codebase, the delay period is set to 30 minutes, which is not significantly different from the recommended 15 or 20 minutes.

Unless the delay period is set to zero (As what happened to Liquity in the past - https://www.liquity.org/blog/tellor-issue-and-fix) OR the delay period is set to an excessively long period such as more than 24 hours or 1 week, it could be justified as a Medium. Otherwise, a Low is more appropriate.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> For context, the longer the delay period, the less likely a fake price will go through, as fake pricing will likely be disputed. In exchange, the price might be lagged behind the market price. Thus, there is a trade-off between the volatility of an asset and the dispute time. The recommended delay period I have seen from online texts/documentation ranges between 15 min and 20 min. 
> 
> However, in the current codebase, the delay period is set to 30 minutes, which is not significantly different from the recommended 15 or 20 minutes.
> 
> Unless the delay period is set to zero (As what happened to Liquity in the past - https://www.liquity.org/blog/tellor-issue-and-fix) OR the delay period is set to an excessively long period such as more than 24 hours or 1 week, it could be justified as a Medium. Otherwise, a Low is more appropriate.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by AdigunQ** [comment]
This escalation should be reconsidered. At no point in the report was a 20-minute recommendation made; it specifically mentioned 15 minutes. Moreover, asserting that a 15-minute window isn't significant is surprising. Within such a window, prices can undergo substantial changes, especially during significant market events. Doubling this to 30 minutes only magnifies potential discrepancies.

The core of this discussion revolves around the trade-off between asset volatility and dispute time. As highlighted earlier, a 15-minute window can witness significant price movement. If other systems, such as Liquity, have chosen a 15-minute balance, after a well thought and careful analysis, then there must be solid reasons to it. Saying it's not a big deal without any insights isn't right.

**Comment by Trumpero** [comment]
I support @AdigunQ's comment in this case. There is likely a specific rationale for the Liquity team's choice of the 15-minute time frame.

**Comment by Evert0x** [comment]
In my opinion this issue is just describing how to code works and it proposed a new solution with different trade offs. 

30 minutes = more lag, less risk of a fake price
15 minutes = less lag, more risk of a fake price

>  If other systems, such as Liquity, have chosen a 15-minute balance, after a well thought and careful analysis, then there must be solid reasons to it. 

The reasons are unclear to me. What is the exact increased risk?

**Comment by Evert0x** [comment]
If no response is provided I'm planning to accept the escalation and invalidate the issue

**Comment by AdigunQ** [comment]
> If no response is provided I'm planning to accept the escalation and invalidate the issue



> In my opinion this issue is just describing how to code works and it proposed a new solution with different trade offs.
> 
> 30 minutes = more lag, less risk of a fake price 15 minutes = less lag, more risk of a fake price
> 
> > If other systems, such as Liquity, have chosen a 15-minute balance, after a well thought and careful analysis, then there must be solid reasons to it.
> 
> The reasons are unclear to me. What is the exact increased risk?

The questions you asked seems confusing...having you been following the conversation all along ?

**Comment by AdigunQ** [comment]
The issue centre around the delay period which is 30 minutes reporting it as too long with a trade-off between volatility of the asset and the dispute time. 

The Escalation raised was that the delay period which is 30 minutes is not significantly different from the recommended 15 minutes, there is no mention of 20 minutes in the report. 

Now, the point is, the escalator failed to provide reasons beyond reasonable doubt as to why 30 minutes is insignificantly different from 15 minutes.

And here in the report, it referenced a well known project in the space, Liquity who carried out a research and come to the conclusion that 15 minutes is actually the best time considering trade-off between volatility of the asset and dispute time. 

Please check the below resources for more info:

https://github.com/liquity/dev/security/advisories/GHSA-5x6p-646h-mmgj


Your understanding of the situation, "30 minutes = more lag, less risk of a fake price, 15 minutes = less lag, more risk of a fake price", seems more like just a literal understanding of what is on ground

The recommended 15 minutes duration was after a clear thought and observation by Liquity again considering the trade-off between volatility of the asset and the dispute time. 

 Even in another report, there is a claim that the Tellor Dev team as well suggest it to be 15 minutes.

Let's not waste time on this any longer, rent is due.

**Comment by Evert0x** [comment]
> Referenced a well known project in the space, Liquity who carried out a research and come to the conclusion that 15 minutes is actually the best time considering trade-off between volatility of the asset and dispute time.

I know, that's the reason why this issue has been submitted. 

But in general, just because another protocol uses X doesn't mean every protocol needs to use X. 

It has not been mentioned in the report why Tokemak benefits from using X (or which risks it exactly mitigates). 

> There is likely a specific rationale for the Liquity team's choice of the 15-minute time frame.

This is basically the final statement. "There is likely a rationale" is not a good reason.

**Comment by Evert0x** [comment]
@AdigunQ @Trumpero will make a final decision within 48 hours

**Comment by Evert0x** [comment]
I've looked at the duplicates as well. It basically comes down to a suggestion to change the value from 30 minutes to 15 minutes as 15 minutes is considered safe. 

I don't see a reason for Medium severity.

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/744/#issuecomment-1748029039): accepted
