### ISSUE TITLE
ctf_sec - LiquidationRow#claimReward can revert in case of negative token rebasing

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#878]
ctf_sec

medium

# LiquidationRow#claimReward can revert in case of negative token rebasing
## Summary

LiquidationRow#claimReward can revert in case of token rebasing

## Vulnerability Detail

In LiquidationRow.sol#claimsVaultRewards

we are calling

```solidity
    function claimsVaultRewards(IDestinationVault[] memory vaults)
        external
        nonReentrant
        hasRole(Roles.LIQUIDATOR_ROLE)
    {
        if (vaults.length == 0) revert Errors.InvalidParam("vaults");

        for (uint256 i = 0; i < vaults.length; ++i) {
            uint256 gasBefore = gasleft();
            IDestinationVault vault = vaults[i];

            destinationVaultRegistry.verifyIsRegistered(address(vault));

            (uint256[] memory amounts, address[] memory tokens) = vault.collectRewards();

            uint256 tokensLength = tokens.length;
            for (uint256 j = 0; j < tokensLength; ++j) {
                address token = tokens[j];
                uint256 amount = amounts[j];
                if (amount > 0 && token != address(0)) {
                    // slither-disable-next-line reentrancy-no-eth
                    _increaseBalance(address(token), address(vault), amount);
                }
            }
            uint256 gasUsed = gasBefore - gasleft();
            emit GasUsedForVault(address(vault), gasUsed, bytes32("claim"));
        }
    }
```

note the validation

```solidity
 _increaseBalance(address(token), address(vault), amount);
```

this calls

```solidity
    function _increaseBalance(address tokenAddress, address vaultAddress, uint256 balance) internal {
        Errors.verifyNotZero(balance, "balance");

        uint256 currentBalance = balances[tokenAddress][vaultAddress];
        uint256 totalBalance = totalTokenBalances[tokenAddress];
        uint256 newTotalBalance = totalBalance + balance;

        // ensure that this contract has enough balance to cover the new total balance
        uint256 balanceOfToken = IERC20(tokenAddress).balanceOf(address(this));
        // @audit
        // rebase token
        if (newTotalBalance > balanceOfToken) {
            /**
             * @dev This should never happen, but just in case. The error is raised if the updated total balance of a
             * specific token in the contract is greater than the actual balance of that token held by the
             * contract.
             * The calling contract should transfer the funds first before updating the balance.
             */

            revert Errors.InsufficientBalance(tokenAddress);
        }
```

but according to the contest readme docs, the protocol is intended to support rebasing token

> Are there any REBASING tokens interacting with the smart contracts?

> Yes, stETH (Lido Staked Ether)

the stETH can undergoes negative rebase and reduce the balance, in this case, the [check below will revert](https://github.com/Tokemak/v2-core-audit-2023-07-14/blob/62445b8ee3365611534c96aef189642b721693bf/src/liquidation/LiquidationRow.sol#L299) and block LiquidationRow#claimReward if the balane of the stETH is reduced

```solidity
uint256 balanceOfToken = IERC20(tokenAddress).balanceOf(address(this));
// @audit
// rebase token
if (newTotalBalance > balanceOfToken) {
```

https://docs.lido.fi/guides/steth-integration-guide#accounting-oracle

> Normally, stETH rebases happen daily when the Lido oracle reports the Beacon chain ether balance update. The rebase can be positive or negative, depending on the validators' performance. In case Lido's validators get slashed or penalized, the stETH balances can decrease according to penalty sizes

## Impact

LiquidationRow#claimReward can revert in case of token rebasing

## Code Snippet

https://github.com/Tokemak/v2-core-audit-2023-07-14/blob/62445b8ee3365611534c96aef189642b721693bf/src/liquidation/LiquidationRow.sol#L125

https://github.com/Tokemak/v2-core-audit-2023-07-14/blob/62445b8ee3365611534c96aef189642b721693bf/src/liquidation/LiquidationRow.sol#L299

## Tool used

Manual Review

**Comment by JeffCX** [comment]
Escalate

Politely dispute severity is medium because when negative rebase happens, the underflow block claim reward -> lock reward

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Politely dispute severity is medium because when negative rebase happens, the underflow block claim reward -> lock reward

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
Hello @JeffCX,

I believe that the stETH won't serve as a reward in the present external protocol that tokemak engages with. Here are my reasons:

* Concerning AURA / CONVEX: The reward contract's details can be located [here](https://github.com/convex-eth/platform/blob/main/contracts/contracts/BaseRewardPool.sol). If a rebase token is one of the rewards, it would disrupt the reward mechanism of these protocols, leading me to believe that they wouldn't incorporate a rebase token as their reward.

* Regarding CRV: One of the rewardPools can be accessed via this [link](https://etherscan.io/address/0x182b723a58739a9c974cfdb385ceadb237453c28#code). When the `rewardPool.claim_rewards(account)` is activated at this [line](https://github.com/Tokemak/v2-core-audit-2023-07-14/blob/62445b8ee3365611534c96aef189642b721693bf/src/destinations/adapters/rewards/CurveRewardsAdapter.sol#L57), the rewardPool initiates an external call to this [contract](https://etherscan.io/address/0x4F48031B0EF8acCea3052Af00A3279fbA31b50D8#code), which resembles the CONVEX reward contract.

* Concerning Maverick: You can locate the Maverick's rewarder through this [link](https://etherscan.deth.net/address/0x14edfe68031bBf229a765919EB52AE6F6F3347d4#code). If a rebase token is utilized as a reward, it would impact the calculation of the `rewardRate` when the function `notifyAndTransfer()` is triggered.

**Comment by JeffCX** [comment]
Agree with the judge's comment, thanks for reviewing the report!

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low based on the above comments.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [JEFFCX](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/878/#issuecomment-1745236072): rejected
