### ISSUE TITLE
Bauchibred - safeApprove breaks logic and functions in many locations

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#880]
Bauchibred

medium

# safeApprove breaks logic and functions in many locations

## Summary

safeApprove will revert if there is any leftover allowance. This causes potential broken logic in many spots.

## Vulnerability Detail

`safeApprove()` method of reverts in the following scenario.

```solidity
require((value == 0) || (token.allowance(address(this), spender) == 0),
"SafeERC20: approve from non-zero to non-zero allowance");
```

Multiple instances of safeApprove is being used in protocol, if any of these instances do not use full allowance then subsequent call to these actions would fail

## Impact

Subsequent calls to these actions would fail if all allowance is not previously used. Users will be unable to make swaps in these instances

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/swapper/adapters/CurveV1StableSwap.sol#L48

https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/vault/DestinationVault.sol#L272

https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/vault/libs/LMPDebt.sol#L327

https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/swapper/adapters/UniV3Swap.sol#L54

https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/vault/LMPVaultRouterBase.sol#L35

https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/swapper/adapters/BalancerV2Swap.sol#L62

https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/utils/PeripheryPayments.sol#L36

https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/swapper/adapters/CurveV2Swap.sol#L42

https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/libs/LibAdapter.sol#L19-L25

## Tool used

Manual Audit

## Recommendation

Check if current allowance is enough and only increase if needed, and if going to be increased, then allowance should first be set to 0 and then needed value or constantly use the [lib provided `_approve()`](https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/libs/LibAdapter.sol#L19-L25)

**Comment by Bauchibred** [comment]
Escalate

I'd like to escalate this issue as a dup of https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/709 and the likes if it gets  accepted. 

I also do not understand judge's comment

> low, lack of proof which makes the existing approval != 6

Sherlock has previously validated issues that just talk about the generic nature of `safeApprove` reverting if there is any left over allowance without showing proof on how the allowances get left over, an instance could be this: https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/141, multiple others exist too.

As seen based on submissions for this contest on "safeApprove reverting" this was massively duplicated and rewards would be diminished to minute values which is why i focused on making my report as minimal as possible and include all the instances where this could affect protocol.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I'd like to escalate this issue as a dup of https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/709 and the likes if it gets  accepted. 
> 
> I also do not understand judge's comment
> 
> > low, lack of proof which makes the existing approval != 6
> 
> Sherlock has previously validated issues that just talk about the generic nature of `safeApprove` reverting if there is any left over allowance without showing proof on how the allowances get left over, an instance could be this: https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/141, multiple others exist too.
> 
> As seen based on submissions for this contest on "safeApprove reverting" this was massively duplicated and rewards would be diminished to minute values which is why i focused on making my report as minimal as possible and include all the instances where this could affect protocol.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
Hello @Bauchibred, I would recommend reviewing ["Scenario A" of "Duplication rules"](https://docs.sherlock.xyz/audits/judging/judging#ix.-duplication-rules) in the latest Sherlock's judging document. 
> In addition to this, there is a submission D which identifies the core issue but does not clearly describe the impact or an attack path. Then D is considered low.

Your submission did not provide a description of the attack path, which is similar to "submission D" in this instance. This is why I have categorized your report as having a low severity in this case.

**Comment by Bauchibred** [comment]
Appreciate judge's time for having another look and while it's worth noting that historically, several reports of this nature have been acknowledged and validated on Sherlock, I agree with judge's POV and completely understand how the report is like a _"submission D"_ in the present context.

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue state as the report lacks a detailed scenario in which this harms the protocol.

**Comment by Bauchibred** [comment]
Hi @Evert0x, your stance is valid, I'd improve the quality of my reports in the future, thanks for taking a look.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Bauchibred](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/880/#issuecomment-1748837892): rejected
