### ISSUE TITLE
ctf_sec - balancer admin can block fund withdraw infinitely by pause the pool

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-06-tokemak-judging#899]
ctf_sec

high

# balancer admin can block fund withdraw infinitely by pause the pool
## Summary
balancer admin can block fund withdraw infinitely by pause the pool

## Vulnerability Detail
in BalancerAuraDestinationVault.sol
```solidity
 uint256[] memory minAmounts = new uint256[](poolTokens.length);
        tokens = _convertToAddresses(poolTokens);
        configurable in initialization so we can target WETH and avoid a swap
            )
            : BalancerBeethovenAdapter.removeLiquidityImbalance(
                balancerVault,
                balancerPool,
                underlyerAmount,
                BalancerUtilities._convertERC20sToAddresses(poolTokens),
                minAmounts
            );amounts = isComposable
            ? BalancerBeethovenAdapter.removeLiquidityComposableImbalance(
                balancerVault,
                balancerPool,
                underlyerAmount,
                BalancerUtilities._convertERC20sToAddresses(poolTokens),
                minAmounts,
```
the above snippet calls into the following snippet from balancer

https://etherscan.io/address/0x32296969Ef14EB0c6d29669C550D4a0449130230#code#F21#L413
```solidity
             if (kind == ExitKind.EXACT_BPT_IN_FOR_ONE_TOKEN_OUT) {
            return _exitExactBPTInForTokenOut(balances, userData);
        } else if (kind == ExitKind.EXACT_BPT_IN_FOR_TOKENS_OUT) {
            return _exitExactBPTInForTokensOut(balances, userData);
        } else {
            // ExitKind.BPT_IN_FOR_EXACT_TOKENS_OUT
            return _exitBPTInForExactTokensOut(balances, scalingFactors, userData);
        }
```

in each function `_exitExactBPTInForTokenOut`,  ` _exitExactBPTInForTokensOut`,  and `_exitBPTInForExactTokensOut` there exists a `whenNotPaused` modifier.

 the balancer vault admin can pause a specific pool to not let user remove liquidity and withdraw fund
 
 > In case of external protocol integrations, are the risks of external contracts pausing or executing an emergency withdrawal acceptable? If not, Watsons will submit issues related to these situations that can harm your protocol's functionality.

> Pausing or emergency withdrawals are not acceptable for Tokemak.

## Impact
 the balancer vault admin can pause a specific pool to not let user remove liquidity and withdraw fund
## Code Snippet
https://github.com/Tokemak/v2-core-audit-2023-07-14/blob/62445b8ee3365611534c96aef189642b721693bf/src/vault/BalancerAuraDestinationVault.sol#L167-L194
## Tool used

Manual Review

## Recommendation
tokemak does not accept the pausing of a pool, a solution can be to remove integration or add checks to see if pool is paused

**Comment by JeffCX** [comment]
Escalate

> In case of external protocol integrations, are the risks of external contracts pausing or executing an emergency withdrawal acceptable? If not, Watsons will submit issues related to these situations that can harm your protocol's functionality.

> Pausing or emergency withdrawals are not acceptable for Tokemak.

so I politely want to dispute as a medium

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> > In case of external protocol integrations, are the risks of external contracts pausing or executing an emergency withdrawal acceptable? If not, Watsons will submit issues related to these situations that can harm your protocol's functionality.
> 
> > Pausing or emergency withdrawals are not acceptable for Tokemak.
> 
> so I politely want to dispute as a medium

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
Hi @JeffCX, based on this comment of sponsors in the contest channel, I think this issue should be marked as low/invalid: 
https://discord.com/channels/812037309376495636/1130514263522410506/1143588977962647582
<img width="1102" alt="Screenshot 2023-10-07 at 15 01 02" src="https://github.com/sherlock-audit/2023-06-tokemak-judging/assets/114548871/317edd8a-36c8-430d-968a-865310a57c4c">

**Comment by JeffCX** [comment]
Sponsor said emergency withdrawal or pause is an unacceptable risk.

Did you read it as "acceptable" sir?

I mean even if the argument is the sponsor is aware that balancer admin can do that,

there is no doc mentioning and the issue is not listed in the known risk

so based on sherlock rules, docs overwrites the discord message

**Comment by 0xSurena** [comment]
[In case of external protocol integrations, are the risks of external contracts pausing or executing an emergency withdrawal acceptable? If not, Watsons will submit issues related to these situations that can harm your protocol's functionality.](https://github.com/sherlock-audit/2023-06-tokemak#q-in-case-of-external-protocol-integrations-are-the-risks-of-external-contracts-pausing-or-executing-an-emergency-withdrawal-acceptable-if-not-watsons-will-submit-issues-related-to-these-situations-that-can-harm-your-protocols-functionality)
Pausing or emergency withdrawals are not acceptable for Tokemak.

Issue title : **balancer admin** can block fund **withdraw** infinitely by **pause** the pool.

This is documented on the contest page and `ctf_sec` mentioned this on this [issue](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/862).

**Comment by JeffCX** [comment]
where is the confusion

> [If not, Watsons will submit issues related to these situations that can harm your protocol's functionality.](https://github.com/sherlock-audit/2023-06-tokemak#q-in-case-of-external-protocol-integrations-are-the-risks-of-external-contracts-pausing-or-executing-an-emergency-withdrawal-acceptable-if-not-watsons-will-submit-issues-related-to-these-situations-that-can-harm-your-protocols-functionality)

and sponsor said no Pausing or emergency withdrawals are not acceptable for Tokemak

so I submit the issue when external protocol can execute pause or withdraw to rug fund including tokenmak user

**Comment by JeffCX** [comment]
Did you read "not acceptable" as "acceptable" sir?

**Comment by JeffCX** [comment]
Or I think the judge read the doc as "the submission related to pausing or emergency withdrawals will not be accepted as valid issue"

emm that is not the readme docs means, please read this again sir

> In case of external protocol integrations, are the risks of external contracts pausing or executing an emergency withdrawal acceptable? If not, Watsons will submit issues related to these situations that can harm your protocol's functionality.

> Pausing or emergency withdrawals are not acceptable for Tokemak.

this means the protocol think if external protocol integrations execute pausing or executing an emergency withdrawal, the risk is too large for the protocol to be accepted so all pausing or executing an emergency issue is valid :)

**Comment by xiaoming9090** [comment]
![image](https://github.com/sherlock-audit/2023-06-tokemak-judging/assets/102820284/c9a206e6-c53d-44b0-a66f-180201392fdb)

For ease of judging, I have pasted the relevant messages related to this topic from the contest's discord channel. The wording has been vague since the start of the contest, and one of the Watsons has questioned the sponsors regarding the actual interpretation of the paragraph in the Contest's README.

From the clarification from the sponsor, pausing of external contracts/protocols is not acceptable to them. In other words, any issue highlighting the risk related to external contracts/protocols being paused should be considered valid.

I'm aware that the admin could pause Balancer's Pools, which will affect Tokemak. However, the sponsor has clarified in the public discord channel that they are aware the pools could be paused early in their lifetime (Around 3 months from deployment time. Afterward, it cannot be paused) and will wait until the pools cannot be paused before using them. So, I assume it is considered a known issue and did not bother submitting it, but I might have wrongly assumed it.

Some points for the judges to consider:
1) Should the sponsor's clarification that they are aware of certain issues in the contest's Discord channel be considered known issues for the contest? If yes, this issue should be considered a known issue. Otherwise, this issue should be valid.
2) Should the contest's README be the only source of truth, which overwrites the sponsor's public discord messages? Or the sponsor's public discord messages could serve as additional support/clarification to their contest's README content?

**Comment by JeffCX** [comment]
Yeah I agree with the senior watson's comments, very factual based.

will leave it to judge and @hrishibhat

**Comment by Evert0x** [comment]
This shows that discord messages from protocol team (in contest channel or dm) is missing from the `Hierarchy of truth` section here https://docs.sherlock.xyz/audits/judging/judging#iii.-some-standards-observed

**Comment by JeffCX** [comment]
> This shows that discord messages from protocol team (in contest channel or dm) is missing from the `Hierarchy of truth` section here https://docs.sherlock.xyz/audits/judging/judging#iii.-some-standards-observed

do you mean the message from channel or dm's priority is higher than contest readme? 

if you think so, that rule should impact the upcoming contest, not the past one :)

**Comment by JeffCX** [comment]
also if the channel message or dm's priority, that defeats the purpose of readme, if sponsor says oh we discover this issue in external audit already, then it is not fair for auditing who put in the work during the contest :)

**Comment by Evert0x** [comment]
I'm Just stating that the info is missing from the judging guidelines.

**Comment by JeffCX** [comment]
> I'm Just stating that the info is missing from the judging guidelines.

ok, got it.

thanks for taking the head of judging role, and looking forward to see the escalation results. 🙏

**Comment by Evert0x** [comment]
Thank you for writing it up @xiaoming9090 

> Should the sponsor's clarification that they are aware of certain issues in the contest's Discord channel be considered known issues for the contest?

Strictly speaking, my answer would be no. Otherwise it will allow the protocol to share any issue they found during the contest and nullify the effort of Watsons who have already found the issue. 

> Should the contest's README be the only source of truth, which overwrites the sponsor's public discord messages? Or the sponsor's public discord messages could serve as additional support/clarification to their contest's README content?

The protocol should be able to clarify protocol intentions in the discord channel during the contest. But when the comments contradict the README it creates a lot of confusion, which happened here. 

Will come back to this at a later moment.

**Comment by JeffCX** [comment]
appreciate the efforts

Not sure if I can help to resolve confusion

the original escalation is to escalate the severity from low to medium

I think the argument to make this issue a valid medium is still straightforward

because in the contest readme

> In case of external protocol integrations, are the risks of external contracts pausing or executing an emergency withdrawal acceptable? If not, Watsons will submit issues related to these situations that can harm your protocol's functionality.

> Pausing or emergency withdrawals are not acceptable for Tokemak.

while balancer withdraw can be paused to lock tokenmak user's fund 👍 🙏

**Comment by Evert0x** [comment]
First of all, as Watson are able to seek clarification in the contest channel. The protocol team is also able to provide it.

> But when the comments contradict the README it creates a lot of confusion, which happened here.

This was my previous statement, but I now that I re-read it I think the protocol comment less contradicting.

Original statement from the protocol (README)
> Pausing or emergency withdrawals are not acceptable for Tokemak.

Clarified statement (based on my interpretation). Based on a message 7 days before contest ended
> Pausing or emergency withdrawals are not acceptable for Tokemak. But it is a known issue that Balancer pools can not be used early in their lifetime. 

Based on this I would think this issue deserves to stay closed.

But second of all, the in-scope balancer pools are listed in the README
```
Balancer wstETH/WETH: 0x32296969Ef14EB0c6d29669C550D4a0449130230
Balancer wstETH/sfrxETH/rETH: 0x5aEe1e99fE86960377DE9f88689616916D5DcaBe
Balancer wstETH/cbETH: 0x9c6d47Ff73e0F5E51BE5FD53236e3F595C5793F2
Balancer rETH/WETH: 0x1E19CF2D73a72Ef1332C882F20534B6519Be0276
```
None of these pools are explicitly mentioned in the issue. Does this issue apply to any of them?

@JeffCX

**Comment by JeffCX** [comment]
We can use the pool below as an example

this issue certain applies to 

Balancer wstETH/sfrxETH/rETH: 0x5aEe1e99fE86960377DE9f88689616916D5DcaBe

the type of the pool is ComposableStablePool

I think working through the function call top down can help

it the pool is compostable, we are callling this [removeLiquidityComposableImbalance](https://github.com/Tokemak/v2-core-audit-2023-07-14/blob/62445b8ee3365611534c96aef189642b721693bf/src/vault/BalancerAuraDestinationVault.sol#L178)

this calls [_withdraw](https://github.com/Tokemak/v2-core-audit-2023-07-14/blob/62445b8ee3365611534c96aef189642b721693bf/src/destinations/adapters/BalancerBeethovenAdapter.sol#L240)

then we atttempts to call [exitPool](https://github.com/Tokemak/v2-core-audit-2023-07-14/blob/62445b8ee3365611534c96aef189642b721693bf/src/destinations/adapters/BalancerBeethovenAdapter.sol#L311)

```solidity
vault.exitPool(
	poolId,
	address(this), // sender,
	payable(address(this)), // recipient,
	request
);
```

then we trigger this [line of code](https://etherscan.io/address/0x5aEe1e99fE86960377DE9f88689616916D5DcaBe#code#F22#L376) in the balancer smart contract

and if the pool is paused, we are [hitting the check](https://etherscan.io/address/0x5aEe1e99fE86960377DE9f88689616916D5DcaBe#code#F22#L401)

```solidity
_beforeSwapJoinExit();
```

```solidity
 function _beforeSwapJoinExit() internal virtual {
        // All joins, exits and swaps are disabled (except recovery mode exits).
        _ensureNotPaused();
    }
```

note when the pool is paused, the check [_ensureNotPaused](https://etherscan.io/address/0x5aEe1e99fE86960377DE9f88689616916D5DcaBe#code#F36#L105) always revert and block withdrawal

```solidity
   /**
     * @dev Reverts if the contract is paused.
     */
    function _ensureNotPaused() internal view {
        _require(_isNotPaused(), Errors.PAUSED);
    }
```

**Comment by JeffCX** [comment]
@Evert0x 

Just want to add the info here for transparency

the protocol team is correct that the pause feature in balancer vault has a pause window

and the pause window is already expires

https://etherscan.io/address/0x5aEe1e99fE86960377DE9f88689616916D5DcaBe#readContract

there is a function called

<img width="566" alt="Screenshot 2023-10-30 at 1 10 12 PM" src="https://github.com/sherlock-audit/2023-06-tokemak-judging/assets/25846666/88753cba-8fa6-4a59-b2fb-8aa13444526c">

the current utc time is already 1698685517

so the admin of the balancer cannot really pause the pool, when they pause the transaction will revert in this [line of code](https://etherscan.io/address/0x5aEe1e99fE86960377DE9f88689616916D5DcaBe#code#F36#L93)

```
function _setPaused(bool paused) internal {
        if (paused) {
            _require(block.timestamp < _getPauseWindowEndTime(), Errors.PAUSE_WINDOW_EXPIRED);
        } else {
            _require(block.timestamp < _getBufferPeriodEndTime(), Errors.BUFFER_PERIOD_EXPIRED);
        }

        _paused = paused;
        emit PausedStateChanged(paused);
    }
```

pause revert here

```solidity
_require(block.timestamp < _getPauseWindowEndTime(), Errors.PAUSE_WINDOW_EXPIRED);
```

so I think this issue and the duplicates is invalid

**Comment by Evert0x** [comment]
Result:

Invalid
Has Duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [JEFFCX](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/899/#issuecomment-1745266673): rejected
