### ISSUE TITLE
ArmedGoose - User vs protocol slippage mismatch on internal swaps will cause certain types of withdrawals to fail

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#90]
ArmedGoose

medium

# User vs protocol slippage mismatch on internal swaps will cause certain types of withdrawals to fail
## Summary
Users can specify a slippage for their withdrawals and redeems. The protocol, when swapping assets internally, doesn't stick to this condition. This mismatch will lead to frequent transaction failures, causing users to waste gas and face difficulties in accessing their funds. 

## Vulnerability Detail
Due to internal slippage set to 100% (no minimal amount) on certain internal swaps, the protocol acts as an "irresponsible cashier" on these internal swaps. Let me explain the core point before moving to the technical details:

- Imagine that at a store, you want to trade a $100 gift card for at least $95 worth of items. The cashier will fetch these items himself. 
- But when fetching items, he ignores your request and bring back only $90 worth. 
- You refuse to accept that and ask for retry but the result is the same again and again, wasting your time and effort.

- The store/cashier is the protocol and the gift card is user shares. The damaged goods are tokens swapped with 100% slippage. The refusal is the slippage check in the entry point (router).

In other words, there is no slippage limit on internal swaps, but some withdraw transactions will revert if the swaps will be unfavourable. It is somewhat like saying "execute a swap with any possible slippage, but if there really will be slippage, then I do not accept it".

For instance let's consider exact flow of `redeem` to analyze the execution flow here.
The flow for `withdraw` is very similar, just at the beginning user specifies maxSharesOut but they are also subject to calculation to corresponding amount of assets, which later has to be satisfied by the protocol when pulling funds out of destinations. Please see the description of the `redeem` exemplary flow below:

- `withdrawBaseAsset()` call is initiated by an user calling a [redeem](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVaultRouterBase.sol#L93C13-L93C14) from the `Router` component (or any other wrapper to these routines).

- The parameters specified by user and relevant here are `shares` which is how many shares user is willing to give back to receive funds, and `minAmountOut` which is acting as slippage protection and allows user to set a minimum amount of tokens received back, otherwise the routine [reverts at the end](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVaultRouterBase.sol#L102-L104).

- This routine call the underlying LMPVault's function [withdraw](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L400), which calls [_withdraw()](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L448) in the same contract. Parameters to `withdraw` are: `possibleAssets = previewRedeem(shares)` so a precomputed value based on calculation how many assets user is likely to receive, and `shares` which is passed from the first call - number of shares user wants to sacrifice.

- Now, the vulnerability lies in [LMPVault's _withdraw](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L448) and related subroutines. In order to undestand it, again there are highlighted key operations:
   - There is a check for idle assets. If there is not enough for them to satisfy `assets` amount, we proceed further. In order for vulnerable condition to occur, there should be insufficient idle assets and the required assets should be pulled from destinations.
   - For each destination in the queue, following operation is performed:
      - `sharesToBurn` and `totalDebtBurn` are calculated based on user shares' part in total shares and their value in function `_calcUserWithdrawSharesToBurn`.  Note, that the protocol assumes that the received tokens and debtBurn will be equal to that calculation, which does not consider slippage will occur.

      - a `withdrawBaseAsset` which is the root cause of this issue, there are following issues:
         - `_burnUnderlyer` uses zero-slippage check on liquidity removal. For instance, for this example lets assume we use [BalancerAuraDestinationVault](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/BalancerAuraDestinationVault.sol#L173-L185) which executes a swap with minimum expected amount of `0`. Let's assume this swap suffered some slippage and we received less tokens than expected.
         - now there's another swap in [Line 273](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/DestinationVault.sol#L273) if some of received tokens is not a base one, then again an unprotected swap (with 0 expected amount) is executed. 
         - At the end, the amount of tokens received from these operations is accepted as it is, so let's go back one step higher back to the point where the "get back tokens" operation was initiated, so at incoming balance check in [LMPVault](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L482-L487).
         - `totalAssetsPulled` are counted based on [incoming balance change](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L487-L489). That means, if the swaps were unfavourable, simply there is less balance received.
         - In lines [493](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L493) and [502](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L502) there are two conditions that may break out of the loop, both occur if the `totalAssetsToPull` is satisfied, which is the previous precomputed amount of assets to receive not including any slippage.
         - if the amount of `totalAssetsToPull` is not satisfied, the loop iterates once again, and once again, until it collects require amount at some point. 
      

## Impact
The slippage mismatch will lead to frequent transaction failures, causing users to waste gas and face difficulties in accessing their funds. 

## Code Snippet

There are several places where such slippage occurs at cost of the protocol:

- in [DestinationVault::withdrawBaseAsset](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/DestinationVault.sol#L273) `swapForQuote` is called with last argument being 0, and in [SwapRouter](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/swapper/SwapRouter.sol#L67) this is the argument responsible for minimal amount:

```solidity
    function swapForQuote(
        address assetToken,
        uint256 sellAmount,
        address quoteToken,
        uint256 minBuyAmount
    ) external onlyDestinationVault(msg.sender) nonReentrant returns (uint256) {
```
- in [BalancerAuraDestinationVault::_burnUnderlyer](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/BalancerAuraDestinationVault.sol#L167)

```solidity
        amounts = isComposable
            ? BalancerBeethovenAdapter.removeLiquidityComposableImbalance(
                balancerVault,
                balancerPool,
                underlyerAmount,
                BalancerUtilities._convertERC20sToAddresses(poolTokens),
                minAmounts,
                0 // TODO: Make this configurable in initialization so we can target WETH and avoid a swap
            )
```

Also in:
 - [CurveConvexDestinationVault](https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/CurveConvexDestinationVault.sol#L183C14-L183C28)
 - and also probably https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/MaverickDestinationVault.sol#L141 

Some of these contracts contain even comments about being safe from slippage, but it is only partially true, because yes the unfavourable swaps will not succeed but the protocol will accept them until the last instruction, where the amount check is done. 

## Tool used

Manual Review

## Recommendation
The maximal slippage could be calculated based on user input to minimum shares or even passed explicitly by user to all subsequent swaps. This would cause all the underlying swaps to be in line with user requirements. So essentially, the slippage has to be enforced on the intermediate swaps too otherwise the protocol will still act like "irresponsible cashier".

Duplicate of #450

**Comment by berndartmueller** [comment]
Escalate

I **do not consider this submission a duplicate** of #519, which demonstrates an arithmetic underflow error rendering withdrawals impossible.

While this submission highlights slippage issues during withdrawals

This submission here is likely rather a duplicate of https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/289

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I **do not consider this submission a duplicate** of #519, which demonstrates an arithmetic underflow error rendering withdrawals impossible.
> 
> While this submission highlights slippage issues during withdrawals
> 
> This submission here is likely rather a duplicate of https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/289

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
Commented on #289

**Comment by Evert0x** [comment]
> Commented on #289

Do you mean that the same comment on #289 applies here?

**Comment by Trumpero** [comment]
Agree with the escalation that this issue is not a duplicate of #519 and should be marked as invalid. The slippage check of the router is used to control the returned amount for users, and it doesn't have any vulnerability. Reverting through this slippage check just protects users; the stricter the slippage check (higher minAmountOut), the greater potential for reversion. Additionally, another slippage check in the withdraw function is an intended check of the protocol, which serves as a safety mechanism for their back-end (similar with #450 and #289)

**Comment by Evert0x** [comment]
Planning to accept escalation and remove duplicate state

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #450 
 
Escalation is accepted even if issue is invalid as main issue was valid when the escalation was created.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [berndartmueller](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/90/#issuecomment-1750260437): accepted
